src/main/java/com/mrk/hdcp/web/bean/BarcodeReaderMB.java
package com.mrk.hdcp.web.bean;

import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.faces.bean.ManagedBean;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

import org.neo4j.cypher.internal.compiler.v2_1.functions.Timestamp;

import com.mrk.hdcp.web.daos.CheckInDetailsJpaController;
import com.mrk.hdcp.web.daos.CheckOutDetailsJpaController;
import com.mrk.hdcp.web.daos.PersonsJpaController;
import com.mrk.hdcp.web.daos.VehiclesJpaController;
import com.mrk.hdcp.web.entites.CheckInDetails;
import com.mrk.hdcp.web.entites.CheckOutDetails;
import com.mrk.hdcp.web.entites.Person;
import com.mrk.hdcp.web.entites.Vehicle;
import com.mrk.hdcp.web.util.JsfUtil;

@ManagedBean
@javax.faces.bean.SessionScoped
public class BarcodeReaderMB {

	private Person foundPerson = null;
	private Vehicle foundVehicle = null;
	private PersonsJpaController personsJpaController = new PersonsJpaController();
	private VehiclesJpaController vehiclesJpaController = new VehiclesJpaController();
	private CheckInDetailsJpaController checkInDetailsJpaController = new CheckInDetailsJpaController();
	private CheckOutDetailsJpaController checkOutDetailsJpaController = new CheckOutDetailsJpaController();
	private String notes = "";
	private String barcode;
	private Vector<CheckInDetails> checkedInCars = new Vector<CheckInDetails>();
	private Vector<CheckInDetails> checkedInPeople = new Vector<CheckInDetails>();
	private boolean found = false;

	public BarcodeReaderMB() {
		refershLists();
	}

	private void refershLists() {
		checkedInCars = checkInDetailsJpaController.getCheckInCars();
		checkedInPeople = checkInDetailsJpaController.getCheckInPeople();
		foundPerson = null;
		foundVehicle = null;
		barcode ="";
		notes = "";
	}
	
	public void printDailyReport(){
		Map<String, Object> reportValues = new HashMap<String, Object>();
		reportValues.put("companyId", -1);
		Date d = new  Date();
		Calendar c = Calendar.getInstance();
		c.setTime(d);
		c.set(Calendar.HOUR, 0);
		reportValues.put("fromDate", new java.sql.Timestamp(c.getTimeInMillis()));
		c.set(Calendar.HOUR, 23);
		c.set(Calendar.MINUTE, 59);
		reportValues.put("toDate", new java.sql.Timestamp(c.getTimeInMillis()));
		
		JsfUtil.printReport(reportValues, "/daily.jasper");
	}

	public void serach() {
		if (barcode == null) {
			return;
		}
		if (barcode.startsWith("P-")) {
			foundPerson = personsJpaController.findPerson(Integer.parseInt(barcode.split("P-")[1]));
			foundVehicle = null;
			return;
		}
		if (barcode.startsWith("-")) {
			foundVehicle = vehiclesJpaController.findVehicles(Integer.parseInt(barcode.split("-")[1]));
			foundPerson = null;
			return;
		}
		JsfUtil.showError("Barcode Not Found");
		barcode = "";
	}

	public void checkInIntoParking() {
		if(isCheckedIn()){
			JsfUtil.showError("Already checked in ");
			return;
		}
		CheckInDetails checkInDetails = new CheckInDetails();
		checkInDetails.setCheckInDate(new Date());
		checkInDetails.setInTheParking(true);
		checkInDetails.setNotes(notes);
		if (foundPerson != null) {
			checkInDetails.setPersonId(foundPerson);
		}
		if (foundVehicle != null) {
			checkInDetails.setVehicleId(foundVehicle);
		}
		if(checkInDetails.getPersonId() != null || checkInDetails.getVehicleId() != null){
			checkInDetailsJpaController.create(checkInDetails);
			refershLists();
			JsfUtil.showSucess("Done ");
		}

	}

	public void checkOut() {
		if(!isCheckedIn()){
			JsfUtil.showError("Already checked out ");
			return;
		}
		try {
			EntityManager entityManager = checkOutDetailsJpaController.getEntityManager();
			EntityTransaction transaction = entityManager.getTransaction();
			transaction.begin();
			CheckInDetails checkIn = null;
			if (barcode.startsWith("P-")) {
				checkIn = checkInDetailsJpaController.findCheckInDetailsByPersonId(Integer.parseInt(barcode.split("P-")[1]));
				checkIn.setInTheParking(false);
				checkInDetailsJpaController.edit(checkIn);
			}
			if (barcode.startsWith("-")) {
				checkIn = checkInDetailsJpaController.findCheckInDetailsByVehicleId(Integer.parseInt(barcode.split("-")[1]));
				checkIn.setInTheParking(false);
				checkInDetailsJpaController.edit(checkIn);
			}
			if(checkIn != null){
				CheckOutDetails checkOutDetails = new CheckOutDetails();
				checkOutDetails.setCheckOutDate(new Date());
				checkOutDetails.setNotes(getNotes());
				checkOutDetails.setCheckInId(checkIn.getCheckInId());
				checkOutDetails.setPersonId(foundPerson);
				checkOutDetails.setVehicleId(foundVehicle);
				checkOutDetailsJpaController.create(checkOutDetails);
			}
			transaction.commit();
		} catch (Exception e) {
			JsfUtil.showError(e.getMessage());
			return;
		}
		refershLists();
		JsfUtil.showSucess("Done ");
	}
	
	
	public Person getFoundPerson() {
		return foundPerson;
	}

	public void setFoundPerson(Person foundPerson) {
		this.foundPerson = foundPerson;
	}

	public Vehicle getFoundVehicle() {
		return foundVehicle;
	}

	public void setFoundVehicle(Vehicle foundVehicle) {
		this.foundVehicle = foundVehicle;
	}

	public PersonsJpaController getPersonsJpaController() {
		return personsJpaController;
	}

	public void setPersonsJpaController(PersonsJpaController personsJpaController) {
		this.personsJpaController = personsJpaController;
	}

	public VehiclesJpaController getVehiclesJpaController() {
		return vehiclesJpaController;
	}

	public void setVehiclesJpaController(VehiclesJpaController vehiclesJpaController) {
		this.vehiclesJpaController = vehiclesJpaController;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public boolean isCheckedIn() {
		if (barcode == null || barcode.equals("")) {
			return false;
		}
		if (barcode.startsWith("P-")) {
			CheckInDetails checkInDetails = checkInDetailsJpaController.findCheckInDetailsByPersonId(Integer.parseInt(barcode.split("P-")[1]));
			return checkInDetails != null;
		}
		if (barcode.startsWith("-")) {
			CheckInDetails checkInDetails = checkInDetailsJpaController.findCheckInDetailsByVehicleId(Integer.parseInt(barcode.split("-")[1]));
			return checkInDetails != null;
		}
		return false;
	}

	public String getBarcode() {
		return barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public CheckInDetailsJpaController getCheckInDetailsJpaController() {
		return checkInDetailsJpaController;
	}

	public void setCheckInDetailsJpaController(CheckInDetailsJpaController checkInDetailsJpaController) {
		this.checkInDetailsJpaController = checkInDetailsJpaController;
	}

	public CheckOutDetailsJpaController getCheckOutDetailsJpaController() {
		return checkOutDetailsJpaController;
	}

	public void setCheckOutDetailsJpaController(CheckOutDetailsJpaController checkOutDetailsJpaController) {
		this.checkOutDetailsJpaController = checkOutDetailsJpaController;
	}

	public Vector<CheckInDetails> getCheckedInCars() {
		return checkedInCars;
	}

	public void setCheckedInCars(Vector<CheckInDetails> checkedInCars) {
		this.checkedInCars = checkedInCars;
	}

	public Vector<CheckInDetails> getCheckedInPeople() {
		return checkedInPeople;
	}

	public void setCheckedInPeople(Vector<CheckInDetails> checkedInPeople) {
		this.checkedInPeople = checkedInPeople;
	}

	public boolean isFound() {
		return found;
	}

	public void setFound(boolean found) {
		this.found = found;
	}

	
}

src/main/java/com/mrk/hdcp/web/daos/CheckInDetailsJpaController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mrk.hdcp.web.daos;

import java.io.Serializable;
import java.util.List;
import java.util.Vector;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityNotFoundException;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import com.mrk.hdcp.web.daos.exceptions.NonexistentEntityException;
import com.mrk.hdcp.web.entites.CheckInDetails;
import com.mrk.hdcp.web.entites.Person;
import com.mrk.hdcp.web.entites.Vehicle;

/**
 *
 * @author mkiswani
 */
public class CheckInDetailsJpaController implements Serializable {

    public CheckInDetailsJpaController() {
    	this.emf = Persistence.createEntityManagerFactory("PU");
    }
    private EntityManagerFactory emf = null;

    public EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    public void create(CheckInDetails checkInDetails) {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            Person personId = checkInDetails.getPersonId();
            if (personId != null) {
                personId = em.getReference(personId.getClass(), personId.getPersonId());
                checkInDetails.setPersonId(personId);
            }
            Vehicle vehicleId = checkInDetails.getVehicleId();
            if (vehicleId != null) {
                vehicleId = em.getReference(vehicleId.getClass(), vehicleId.getVehicleId());
                checkInDetails.setVehicleId(vehicleId);
            }
            em.persist(checkInDetails);
            if (personId != null) {
                personId.getCheckInDetailsCollection().add(checkInDetails);
                personId = em.merge(personId);
            }
            if (vehicleId != null) {
                vehicleId.getCheckInDetailsCollection().add(checkInDetails);
                vehicleId = em.merge(vehicleId);
            }
            em.getTransaction().commit();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void edit(CheckInDetails checkInDetails) throws NonexistentEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            CheckInDetails persistentCheckInDetails = em.find(CheckInDetails.class, checkInDetails.getCheckInId());
            Person personIdOld = persistentCheckInDetails.getPersonId();
            Person personIdNew = checkInDetails.getPersonId();
            Vehicle vehicleIdOld = persistentCheckInDetails.getVehicleId();
            Vehicle vehicleIdNew = checkInDetails.getVehicleId();
            if (personIdNew != null) {
                personIdNew = em.getReference(personIdNew.getClass(), personIdNew.getPersonId());
                checkInDetails.setPersonId(personIdNew);
            }
            if (vehicleIdNew != null) {
                vehicleIdNew = em.getReference(vehicleIdNew.getClass(), vehicleIdNew.getVehicleId());
                checkInDetails.setVehicleId(vehicleIdNew);
            }
            checkInDetails = em.merge(checkInDetails);
            if (personIdOld != null && !personIdOld.equals(personIdNew)) {
                personIdOld.getCheckInDetailsCollection().remove(checkInDetails);
                personIdOld = em.merge(personIdOld);
            }
            if (personIdNew != null && !personIdNew.equals(personIdOld)) {
                personIdNew.getCheckInDetailsCollection().add(checkInDetails);
                personIdNew = em.merge(personIdNew);
            }
            if (vehicleIdOld != null && !vehicleIdOld.equals(vehicleIdNew)) {
                vehicleIdOld.getCheckInDetailsCollection().remove(checkInDetails);
                vehicleIdOld = em.merge(vehicleIdOld);
            }
            if (vehicleIdNew != null && !vehicleIdNew.equals(vehicleIdOld)) {
                vehicleIdNew.getCheckInDetailsCollection().add(checkInDetails);
                vehicleIdNew = em.merge(vehicleIdNew);
            }
            em.getTransaction().commit();
        } catch (Exception ex) {
            String msg = ex.getLocalizedMessage();
            if (msg == null || msg.length() == 0) {
                Integer id = checkInDetails.getCheckInId();
                if (findCheckInDetails(id) == null) {
                    throw new NonexistentEntityException("The checkInDetails with id " + id + " no longer exists.");
                }
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void destroy(Integer id) throws NonexistentEntityException {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            CheckInDetails checkInDetails;
            try {
                checkInDetails = em.getReference(CheckInDetails.class, id);
                checkInDetails.getCheckInId();
            } catch (EntityNotFoundException enfe) {
                throw new NonexistentEntityException("The checkInDetails with id " + id + " no longer exists.", enfe);
            }
            Person personId = checkInDetails.getPersonId();
            if (personId != null) {
                personId.getCheckInDetailsCollection().remove(checkInDetails);
                personId = em.merge(personId);
            }
            Vehicle vehicleId = checkInDetails.getVehicleId();
            if (vehicleId != null) {
                vehicleId.getCheckInDetailsCollection().remove(checkInDetails);
                vehicleId = em.merge(vehicleId);
            }
            em.remove(checkInDetails);
            em.getTransaction().commit();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public List<CheckInDetails> findCheckInDetailsEntities() {
        return findCheckInDetailsEntities(true, -1, -1);
    }

    public List<CheckInDetails> findCheckInDetailsEntities(int maxResults, int firstResult) {
        return findCheckInDetailsEntities(false, maxResults, firstResult);
    }

    private List<CheckInDetails> findCheckInDetailsEntities(boolean all, int maxResults, int firstResult) {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            cq.select(cq.from(CheckInDetails.class));
            Query q = em.createQuery(cq);
            if (!all) {
                q.setMaxResults(maxResults);
                q.setFirstResult(firstResult);
            }
            return q.getResultList();
        } finally {
            em.close();
        }
    }

    public CheckInDetails findCheckInDetails(Integer id) {
        EntityManager em = getEntityManager();
        try {
            return em.find(CheckInDetails.class, id);
        } finally {
            em.close();
        }
    }

    public int getCheckInDetailsCount() {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<CheckInDetails> rt = cq.from(CheckInDetails.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
        } finally {
            em.close();
        }
    }

	public CheckInDetails findCheckInDetailsByPersonId(int personId) {
		EntityManager em = getEntityManager();
		try {
			Query createQuery = em.createQuery("Select u from CheckInDetails u where u.personId.personId=:personId and u.inTheParking = true", CheckInDetails.class);
			createQuery.setParameter("personId", personId);
			createQuery.setHint("javax.persistence.cache.storeMode", "REFRESH");
			Object singleResult2 = createQuery.getSingleResult();
			if (singleResult2 != null) {
				CheckInDetails singleResult = (CheckInDetails) singleResult2;
				return singleResult;
			} 
			return null;
		} catch (NoResultException e) {
			return null;
		} finally {
			em.close();
		}
	}

	public CheckInDetails findCheckInDetailsByVehicleId(int vehicleId) {
		EntityManager em = getEntityManager();
		try {
			Query createQuery = em.createQuery("Select u from CheckInDetails u where u.vehicleId.vehicleId=:vehicleId and u.inTheParking = true", CheckInDetails.class);
			createQuery.setParameter("vehicleId", vehicleId);
			createQuery.setHint("javax.persistence.cache.storeMode", "REFRESH");
			Object singleResult2 = createQuery.getSingleResult();
			if (singleResult2 != null) {
				CheckInDetails singleResult = (CheckInDetails) singleResult2;
				if (!singleResult.getInTheParking()) {
					return null;
				}
				return singleResult;
			} 
			return null;
		} catch (NoResultException e) {
			return null;
		} finally {
			em.close();
		}
	}

	public Vector<CheckInDetails> getCheckInCars() {
		EntityManager em = getEntityManager();
		try {
			Query createQuery = em.createQuery("Select u from CheckInDetails u where u.vehicleId.vehicleId is not null AND u.inTheParking = true", CheckInDetails.class);
			createQuery.setHint("javax.persistence.cache.storeMode", "REFRESH");
			Object singleResult = createQuery.getResultList();
			if (singleResult != null) {
				return (Vector<CheckInDetails>) singleResult;
			} 
			return null;
		} catch (NoResultException e) {
			return null;
		} finally {
			em.close();
		}
	}

	public Vector<CheckInDetails> getCheckInPeople() {
		EntityManager em = getEntityManager();
		try {

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template.xhtml">

	<ui:define name="content">
		<style>
.thumb {
	width: 150px;
	height: 150px;
	border-radius: 150px;
	-webkit-border-radius: 150px;
	-moz-border-radius: 150px;
}
</style>
		<h:form id="vehicleForm">
			<p:ajaxStatus onstart="PF('statusDialog').show()"
				onsuccess="PF('statusDialog').hide()" />
			<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
				closable="false" resizable="false" showHeader="false">
				<p:graphicImage name="images/loading.gif" width="64px" height="64px" />
			</p:dialog>
			<p:growl id="growl" showDetail="false" />
			<h:panelGrid id="container" columns="1" cellpadding="2"
				cellspacing="2">
				<p:fieldset id="vehicleFormFieldset" legend="Scan The Bar Code"
					toggleable="false" toggleSpeed="500">
					<h:panelGrid columns="3" cellpadding="2" cellspacing="2">
					<h:panelGrid columns="3" cellpadding="2" cellspacing="2">
						<h:outputLabel value="Bar Code" />
						<p:password value="#{barcodeReaderMB.barcode}" id="barcode" redisplay="true"/>
					</h:panelGrid>
					<h:panelGroup style="text-align: center;">
						
						<p:commandButton id="find" process="@this barcode"
							action="#{barcodeReaderMB.serach}" value="Find"
							update="container growl" icon="ui-icon-document"
							 />
						<p:commandButton id="checkIn" process="@all"
							action="#{barcodeReaderMB.checkInIntoParking}" value="Check In"
							update="vehiclePanelGrid vehicleFormFieldset @this checkout checkedInCars checkedInPpl" icon="ui-icon-document"
							disabled="#{barcodeReaderMB.checkedIn || (barcodeReaderMB.barcode == null) || (barcodeReaderMB.foundPerson == null and barcodeReaderMB.foundVehicle == null)}" oncomplete="$(function(){PrimeFaces.focus('vehicleForm:barcode');});"/>
						<p:commandButton id="checkout" action="#{barcodeReaderMB.checkOut}" process="@all"
							disabled="#{!barcodeReaderMB.checkedIn || (barcodeReaderMB.barcode == null) || (barcodeReaderMB.foundPerson == null and barcodeReaderMB.foundVehicle == null)}"
							value="Check Out"
							update="vehiclePanelGrid growl vehicleFormFieldset @this checkIn checkedInCars checkedInPpl"
							icon="ui-icon-trash" oncomplete="$(function(){PrimeFaces.focus('vehicleForm:barcode');});">
						</p:commandButton>
						<p:commandButton 
							value="Print Daily Report"
							action="#{barcodeReaderMB.printDailyReport}" 
							ajax="false"
							onclick="this.form.target='_blank'" 
							/>
						<p:poll interval="20" update="checkedInCars" />
					</h:panelGroup>
					<h:panelGrid columns="2" cellpadding="2"
						rendered="#{barcodeReaderMB.foundVehicle != null}"
						styleClass="ui-fieldset-legend ui-corner-all ui-state-default"
						width="300px">
						<p:panel>
							<p:graphicImage height="150" width="150px" cache="false"
								value="#{barcodeReaderMB.foundVehicle.image}" styleClass="thumb" />
						</p:panel>
						<h:panelGrid id="vehiclePanelGrid" columns="2" cellpadding="2"
							cellspacing="2">
							<h:outputLabel value="Vehicle Type" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundVehicle.vehicleType}" />

							<h:outputLabel value="Vehicle Model" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundVehicle.vehicleModel}" />

							<h:outputLabel value="Vehicle Plate Number" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundVehicle.vehiclePlateNumber}" />

							<h:outputLabel value="Include Generator ? " />
							<h:outputLabel
								value="#{barcodeReaderMB.foundVehicle.includeGenerator}" />

							<h:outputLabel value="Company" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundVehicle.companyId.companyName}" />


							<h:outputLabel value="Notes" />
							<p:inputText value="#{barcodeReaderMB.notes}" />


							<h:outputLabel value="Include Generator ?" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundVehicle.includeGenerator?'True':'False'}" />

						</h:panelGrid>
					</h:panelGrid>
					<h:panelGrid columns="2" cellpadding="2"
						rendered="#{barcodeReaderMB.foundPerson != null}"
						styleClass="ui-fieldset-legend ui-corner-all ui-state-default"
						width="300px">
						<p:panel>
							<p:graphicImage height="150" width="100px" cache="false"
								value="#{barcodeReaderMB.foundPerson.image}" styleClass="thumb" />
						</p:panel>
						<h:panelGrid id="personPanelGrid" columns="2" cellpadding="2"
							cellspacing="2">
							<h:outputLabel value="Person Name" />
							<h:outputLabel value="#{barcodeReaderMB.foundPerson.personName}" />

							<h:outputLabel value="Person Tel" />
							<h:outputLabel value="#{barcodeReaderMB.foundPerson.personTel}" />

							<h:outputLabel value="Person Address" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundPerson.personAddress}" />

							<h:outputLabel value="Person Photo ID" />
							<h:outputLabel value="#{barcodeReaderMB.foundPerson.personPhotoId}" />

							<h:outputLabel value="Company" />
							<h:outputLabel
								value="#{barcodeReaderMB.foundPerson.companyId.companyName}" />


							<h:outputLabel value="Notes" />
							<p:inputTextarea value="#{barcodeReaderMB.notes}" />


						</h:panelGrid>
					</h:panelGrid>
					
					</h:panelGrid>
				</p:fieldset>
				<h:panelGrid columns="1" cellpadding="2"
					styleClass="ui-fieldset-legend ui-corner-all ui-state-default"
					width="100%">
					<p:dataTable id="checkedInCars" var="car" styleClass="dataTable"
						value="#{barcodeReaderMB.checkedInCars}" paginator="true"
						paginatorPosition="bottom" rows="5">
						<p:column headerText="Company Name">
							<h:outputText value="#{car.vehicleId.companyId.companyName}" />
						</p:column>

						<p:column headerText="Vehicle Plate Number">
							<h:outputText value="#{car.vehicleId.vehiclePlateNumber}" />
						</p:column>

						<p:column headerText="Permement Id">
							<h:outputText value="#{car.vehicleId.vehiclePermementId}" />
						</p:column>

						<p:column headerText="Checkin Time">
							<h:outputText value="#{car.checkInDate}">
								<f:convertDateTime pattern="MM/dd/yyyy hh:mm a" />
							</h:outputText>
						</p:column>

						<p:column headerText="Notes">
							<h:outputText value="#{car.notes}" />
						</p:column>

					</p:dataTable>
					<p:dataTable id="checkedInPpl" var="checkedInPerson" styleClass="dataTable"
						value="#{barcodeReaderMB.checkedInPeople}" paginator="true"
						paginatorPosition="bottom" rows="5">
						<p:column headerText="Company Name">
							<h:outputText value="#{checkedInPerson.personId.companyId.companyName}" />
						</p:column>
						<p:column headerText="Person Name">
							<h:outputText value="#{checkedInPerson.personId.personName}" />
						</p:column>

						<p:column headerText="Person Tel">
							<h:outputText value="#{checkedInPerson.personId.personTel}" />
						</p:column>

						<p:column headerText="Person Address">
							<h:outputText value="#{checkedInPerson.personId.personAddress}" />
						</p:column>

						<p:column headerText="Checkin Time">
							<h:outputText value="#{checkedInPerson.checkInDate}">
								<f:convertDateTime pattern="MM/dd/yyyy hh:mm a" />
							</h:outputText>
						</p:column>

						<p:column headerText="Notes">
							<h:outputText value="#{checkedInPerson.notes}" />
						</p:column>
					</p:dataTable>

				</h:panelGrid>
			</h:panelGrid>
			<script>
				$(function(){PrimeFaces.focus('vehicleForm:barcode');});
			</script>
		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template.xhtml">

	<ui:define name="content">

		<h:form>
			<p:growl id="growl" sticky="true" showDetail="false" life="100" />
			<p:ajaxStatus onstart="PF('statusDialog').show()"
						onsuccess="PF('statusDialog').hide()" /> <p:dialog
						widgetVar="statusDialog" modal="true" draggable="false"
						closable="false" resizable="false" showHeader="false"
						>
						<p:graphicImage name="images/loading.gif" width="64px"
							height="64px" />
					</p:dialog> 
			<p:fieldset legend="User Login">
				<h:panelGrid columns="2" cellpadding="5" id="dlg">
					<h:outputLabel for="email" value="Username" />
					<p:inputText id="email" value="#{loginMB.username}" required="true" label="Email" requiredMessage="Username Required" >
					</p:inputText>

					<h:outputLabel for="password" value="Password" />
					<p:password id="password" value="#{loginMB.password}" required="true" label="password" requiredMessage="Password Required"/>

					<f:facet name="footer">
						<p:commandButton value="Log in" ajax="false" action="#{loginMB.login}" update="@all" process="@all" styleClass="btn" icon="ui-icon-locked"/>
					</f:facet>
				</h:panelGrid>
			</p:fieldset>
		</h:form>

	</ui:define>
</ui:composition>